POST /users HTTP/1.1
Host: localhost:5001
Content-Type: application/json
Accept: application/json

{
    "name": "Christian",
    "loyaltyPoints": 0,
    "settings":{"interests": ["whisky","cycling"]}
}